FinalProjectMyBlog/FinalProjectMyBlog/ViewModels/Account/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Логин не может быть пустым")]
        [EmailAddress]
        [Display(Name = "Email", Prompt = "Введите email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Пароль не может быть пустым")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить?")]
        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/ViewModels/Account/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.ViewModels.Account
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Поле Имя обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Имя", Prompt = "Введите имя")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Поле Фамилия обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Фамилия", Prompt = "Введите фамилию")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Поле Email обязательно для заполнения")]
        [EmailAddress]
        [Display(Name = "Email", Prompt = "example.com")]
        public string EmailReg { get; set; }

        [Required(ErrorMessage = "Поле Год обязательно для заполнения")]
        [Display(Name = "Год", Prompt = "Год")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Поле День обязательно для заполнения")]
        [Display(Name = "День", Prompt = "День")]
        public int? Date { get; set; }

        [Required(ErrorMessage = "Поле Месяц обязательно для заполнения")]
        [Display(Name = "Месяц", Prompt = "Месяц")]
        public int? Month { get; set; }

        [Required(ErrorMessage = "Поле Пароль обязательно для заполнения")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль")]
        [StringLength(100, ErrorMessage = "Поле {0} должно иметь минимум {2} и максимум {1} символов.", MinimumLength = 5)]
        public string PasswordReg { get; set; }

        [Required(ErrorMessage = "Обязательно подтвердите пароль")]
        [Compare("PasswordReg", ErrorMessage = "Пароли не совпадают")]
        [DataType(DataType.Password)]
        [Display(Name = "Подтвердить пароль", Prompt = "Введите пароль повторно")]
        public string PasswordConfirm { get; set; }

        public string Login => EmailReg;
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Controllers/Account/RegisterController.cs
using AutoMapper;
using FinalProjectMyBlog.Models;
using FinalProjectMyBlog.ViewModels.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.Controllers.Account
{
    public class RegisterController : Controller
    {
        private IMapper _mapper;

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public RegisterController(IMapper mapper, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [Route("Register")]
        [HttpGet]
        public IActionResult Register()
        {
            return View("Home/Register");
        }

        [Route("RegisterPart2")]
        [HttpGet]
        public IActionResult RegisterPart2(RegisterViewModel model)
        {
            return View("RegisterPart2", model);
        }

        [Route("Register")]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<User>(model);

                var result = await _userManager.CreateAsync(user, model.PasswordReg);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "Пользователь");
                    await _signInManager.SignInAsync(user, false);
                    //await Authenticate(user);
                    Program.Logger.Info($"Зарегистрирован новый пользователь {user.Email}");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        Program.Logger.Info($"При регистрации пользователя найдены ошибки: {error.Description}");
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            
            Program.Logger.Info($"Ошибки в модели при регистрации пользователя");
            return View("RegisterPart2", model);
        }       
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Controllers/Account/RolesController.cs
using FinalProjectMyBlog.Models;
using FinalProjectMyBlog.ViewModels.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.Controllers.Account
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Controllers/Tags/TagController.cs
using AutoMapper;
using FinalProjectMyBlog.Data.Queries;
using FinalProjectMyBlog.Data.Repository;
using FinalProjectMyBlog.Data.UoW;
using FinalProjectMyBlog.Extentions;
using FinalProjectMyBlog.Models;
using FinalProjectMyBlog.ViewModels.Comments;
using FinalProjectMyBlog.ViewModels.Tags;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.Controllers.Comments
{
    public class TagController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private IMapper _mapper;

        public TagController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }


        [Route("AddTag")]
        [HttpGet]
        public IActionResult AddTag()
        {
            var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

            var model = new TagViewModel();

            model.Tags = repository.GetAllTags();

            return View("AddTag", model);
        }

        [Route("CreateTag")]
        [HttpGet]
        public IActionResult CreateTag()
        {
            return View("CreateTag");
        }

        [Route("CreateTag")]
        [HttpPost]
        public async Task<IActionResult> CreateTag(TagCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag();

                tag.Convert(model);

                var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

                repository.AddTag(tag);

                return RedirectToAction("MyPage", "AccountManager");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные данные");
                return View("CreateTag", model);
            }
        }

        [Route("EditTag")]
        [HttpPost]
        public IActionResult EditTag(string id)
        {
            var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

            var result = repository.GetTagsById(id);

            var editmodel = _mapper.Map<TagEditViewModel>(result);

            return View("EditTag", editmodel);
        }

        [Route("UpdateTag")]
        [HttpPost]
        public IActionResult UpdateTag(
           TagEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

                var tag = repository.GetTagsById(model.Id);

                repository.UpdateTag(
                    tag,
                    new UpdateTagQuery(model.TagName)
                );

                return RedirectToAction("MyPage", "AccountManager");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные данные");
                return View("EditTag", model);
            }
        }

        [Route("DeleteTag")]
        [HttpPost]
        public async Task<IActionResult> DeleteTag(string id)
        {
            var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

            var tag = repository.GetTagsById(id);

            repository.DeleteTag(tag);

            return RedirectToAction("MyPage", "AccountManager");
        }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/Login.cshtml
@model FinalProjectMyBlog.ViewModels.Account.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<div class="block-reg background-white">
    <h4 class="center">Добро пожаловать!</h4>
    <form class="frm" method="post" asp-controller="AccountManager" asp-action="Login">
        <div asp-validation-summary="ModelOnly"></div>
        <div>
            <div class="mrgn">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class="mrgn">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div>
            <input class="enter_submit" type="submit" value="Войти" />
        </div>
    </form>
</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

@model FinalProjectMyBlog.ViewModels.Account.RegisterViewModel

<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

<div class="block-reg background-white">
    <h4 class="center">Впервые с нами?</h4>
    <div class="center text-color-gray">Регистрация нового пользователя</div>
    <form class="frm" method="get" asp-controller="Register" asp-action="RegisterPart2">
        <div asp-validation-summary="ModelOnly"></div>
        <div>
            <div class="mrgn">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class="mrgn">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="text-color-gray text-size_12">Дата рождения</div>
        <div class="mrgn center">
            <select asp-for="Date" class="form-control date_control" ID="ddlDay">
                <option value="">@Model.Date</option>
            </select>
            <span asp-validation-for="Date" class="text-danger"></span>

            <select asp-for="Month" class="form-control date_control" asp-items="Html.GetEnumSelectList<FinalProjectMyBlog.ViewModels.Months>()" onchange="PopulateDays()" ID="ddlMonth">
                <option value="">@Model.Month</option>
            </select>

            <span asp-validation-for="Month" class="text-danger"></span>

            <select asp-for="Year" class="form-control date_control" ID="ddlYear"
                    asp-items="Enumerable.Range(DateTime.Now.AddYears(-100).Year, DateTime.Now.AddYears(-14).Year - DateTime.Now.AddYears(-100).Year).Reverse().Select(x=> new SelectListItem(x.ToString(), x.ToString()))"
                    onchange="PopulateDays()">
                <option value="">@Model.Year</option>
            </select>
            <span asp-validation-for="Year" class="text-danger"></span>
        </div>

        <div class="center">
            <input class="btn_submit" type="submit" value="Продолжить регистрацию" />
        </div>
    </form>

    @Model.Month

    <script src="http://code.jquery.com/jquery-latest.js"></script>

    <script type="text/javascript">
        function PopulateDays() {
            var ddlMonth = document.getElementById("ddlMonth");
            var ddlYear = document.getElementById("ddlYear");
            var ddlDay = document.getElementById("ddlDay");

            var y = ddlYear.options[ddlYear.selectedIndex].value;
            var m = ddlMonth.options[ddlMonth.selectedIndex].value != 0;
            if (ddlMonth.options[ddlMonth.selectedIndex].value != 0 && ddlYear.options[ddlYear.selectedIndex].value != 0) {
                var dayCount = 32 - new Date(ddlYear.options[ddlYear.selectedIndex].value, ddlMonth.options[ddlMonth.selectedIndex].value - 1, 32).getDate();
                ddlDay.options.length = 0;
                for (var i = 1; i <= dayCount; i++) {
                    AddOption(ddlDay, i, i);
                }
            }
        }

        function AddOption(ddl, text, value) {
            var opt = document.createElement("OPTION");
            opt.text = text;
            opt.value = value;
            ddl.options.add(opt);
        }
    </script>

</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/_AccessIsDeniedPartial.cshtml
<div class="center">
    <p>Доступ запрещен</p>
</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheBestBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/main-page.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/base-styles.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="background-main">
    <header class="border-bottom header background-white">
        <div class="container">
            <div class="topnav">
                <a asp-area="" asp-controller="Home" asp-action="Index">TheBestBlog</a>
                @if (User.IsInRole("Администратор"))
                {
                    <a asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                }
                @if (User.IsInRole("Администратор") || User.IsInRole("Модератор"))
                {
                    <a asp-area="" asp-controller="Tag" asp-action="AddTag">Теги</a>
                }
                <partial name="_LogoutPartial.cshtml" />
                @if (User.Identity.IsAuthenticated)
                {
                    <partial name="_SearchLayoutPartial" />
                }
                </div>
        </div>
    </header>
    <div class="container background-main">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TheBestBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/_LogoutPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using FinalProjectMyBlog.Models;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<div class="righ-align">
    @if (SignInManager.IsSignedIn(User))
    {@*<button class="enter_submit" asp-area="" asp-controller="AccountManager" asp-action="Logout">Выход</button>*@

    <form method="post" asp-controller="AccountManager" asp-action="Logout">
        <input class="enter_submit" type="submit" value="Выход" />
    </form>}
</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Shared/_SearchLayoutPartial.cshtml
<div class="righ-align">
    <form asp-area="" asp-controller="AccountManager" asp-action="UserList" method="get">
        <i class="fa fa-search"></i>
        <input type="text" placeholder="Поиск" name="search">
    </form>
</div>