FinalProjectMyBlog/FinalProjectMyBlog/Models/Publication.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.Models
{
    public class Publication
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }

        public string CurrentPublicationId { get; set; }

        public Publication CurrentPublication { get; set; }
        public User User { get; set; }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/ViewModels/Publications/PublicationCreateViewModel.cs
using FinalProjectMyBlog.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.ViewModels.Publications
{
    public class PublicationCreateViewModel
    {
        [Required(ErrorMessage = "Поле не может быть пустым")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название публикации")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [DataType(DataType.Text)]
        [Display(Name = "Текст", Prompt = "Введите текст публикации")]
        public string Text { get; set; }

        public List<Tag> Tags { get; set; }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/ViewModels/Publications/PublicationEditViewModel.cs
using FinalProjectMyBlog.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.ViewModels.Publications
{
    public class PublicationEditViewModel
    {
        [Required]
        [Display(Name = "Идентификатор публикации")]
        public string Id { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название публикации")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [DataType(DataType.Text)]
        [Display(Name = "Текст", Prompt = "Введите текст")]
        public string Text { get; set; }

        public List<Tag> Tags { get; set; }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/ViewModels/Publications/PublicationViewModel.cs
using FinalProjectMyBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.ViewModels.Publications
{
    public class PublicationViewModel
    {
        public Publication Publication { get; set; }

        public PublicationViewModel(/*Publication publication*/)
        {
            //Publication = publication;
        }

        public List<Publication> Publications { get; set; }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Controllers/Publications/PublicationController.cs
using AutoMapper;
using FinalProjectMyBlog.Data.Queries;
using FinalProjectMyBlog.Data.Repository;
using FinalProjectMyBlog.Data.UoW;
using FinalProjectMyBlog.Extentions;
using FinalProjectMyBlog.Models;
using FinalProjectMyBlog.ViewModels.Account;
using FinalProjectMyBlog.ViewModels.Publications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectMyBlog.Controllers.Publications
{
    public class PublicationController : Controller
    {
        private readonly UserManager<User> _userManager;
        private IUnitOfWork _unitOfWork;
        private IMapper _mapper;

        public PublicationController(UserManager<User> userManager, IUnitOfWork unitOfWork, IMapper mapper)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [Route("Create")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new PublicationCreateViewModel();

            model.Tags = await GetAllTag();

            return View("Create", model);
        }

        [Route("Create")]
        [HttpPost]
        public async Task<IActionResult> Create(PublicationCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentuser = User;

                var publication = new Publication();

                //сюда нужно добавить сохранение тегов, выбранных чекбоксами

                publication.Convert(model);

                var user = await _userManager.GetUserAsync(currentuser);

                var repository = _unitOfWork.GetRepository<Publication>() as PublicationsRepository;

                repository.AddPublication(user, publication);

                Program.Logger.Info($"Пользователь {user.Email} добавил статью {publication.Title}");

                return RedirectToAction("MyPage", "AccountManager");
            }
            else
            {
                model.Tags = await GetAllTag();
                ModelState.AddModelError("", "Некорректные данные");
                Program.Logger.Info($"Некорректные данные при добавлении пользователем статьи");
                return View("Create", model);
            }
        }

        [Route("EditPublication")]
        [HttpPost]
        public async Task<IActionResult> EditPublication(string id)
        {
            var repository = _unitOfWork.GetRepository<Publication>() as PublicationsRepository;

            var result = repository.GetPublicationsById(id);

            var editmodel = _mapper.Map<PublicationEditViewModel>(result);

            editmodel.Tags = await GetAllTag();

            return View("EditPublication", editmodel);
        }

        [Route("UpdatePublication")]
        [HttpPost]
        public async Task<IActionResult> UpdatePublicationAsync(
            PublicationEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var repository = _unitOfWork.GetRepository<Publication>() as PublicationsRepository;

                var publication = repository.GetPublicationsById(model.Id);

                repository.UpdatePublication(
                    publication,
                    new UpdatePublicationQuery(model.Title, model.Text)
                );

                Program.Logger.Info($"Пользовател отредактировал статью {publication.Id}");

                return RedirectToAction("MyPage", "AccountManager");
            }
            else
            {
                model.Tags = await GetAllTag();
                ModelState.AddModelError("", "Некорректные данные");
                Program.Logger.Info($"Некорректные данные при редактировании статьи");
                return View("EditPublication", model);
            }
        }

        [Route("DeletePublication")]
        [HttpPost]
        public async Task<IActionResult> DeletePublication(string id)
        {
            var repository = _unitOfWork.GetRepository<Publication>() as PublicationsRepository;

            var publication = repository.GetPublicationsById(id);

            string publicationLog = publication.Id;

            repository.DeletePublication(publication);

            Program.Logger.Info($"Пользовател удалил статью {publicationLog}");

            return RedirectToAction("MyPage", "AccountManager");

        }

        [Route("GetAllPublications")]
        [HttpGet]
        public IActionResult GetAllPublications()
        {
            var repository = _unitOfWork.GetRepository<Publication>() as PublicationsRepository;

            var model = new PublicationViewModel();

            model.Publications = repository.GetAllPublications();

            return View("GetAllPublications", model);
        }

        private async Task<List<Tag>> GetAllTag()
        {
            var repository = _unitOfWork.GetRepository<Tag>() as TagsRepository;

            return repository.GetAllTags();
        }
    }
}

FinalProjectMyBlog/FinalProjectMyBlog/Views/Publication/Create.cshtml
@model FinalProjectMyBlog.ViewModels.Publications.PublicationCreateViewModel;


<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

<div class="block-reg background-white">
    <h3 class="center">Создание публикации</h3>
    <form class="frm" method="post" asp-controller="Publication" asp-action="Create">

        <div asp-validation-summary="ModelOnly"></div>
        <div class="lined-block" publicationscontainer>
            <label class="gray-text">Теги</label>

            <div class="publicationsbox">
                @if (Model.Tags.Count != 0)
                {
                    @foreach (var tag in @Model.Tags)
                    {
                <div class="mrgn" style="display:inline-block">
                    <input type="checkbox"><label>@tag.TagName</label><br>                    
                </div>                                                                      
                    }
                }
                else
                {
                    <div>
                        <label> Не добавлено ни одного тега.</label>
                    </div>
                }
            </div>
        </div>
                    <div>
                        <div class="mrgn">
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div>
                        <div class="mrgn">
                            <textarea asp-for="Text" class="form-control"></textarea>
                            <span asp-validation-for="Text" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="center">
                        <input class="btn_submit" type="submit" value="Сохранить" />
                    </div>
     </form>
</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Publication/EditPublication.cshtml
@model FinalProjectMyBlog.ViewModels.Publications.PublicationEditViewModel;


<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

<div class="block-reg background-white">
    <h3 class="center">Редактирование публикации</h3>
    <form class="frm" method="post" asp-controller="Publication" asp-action="UpdatePublication">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="lined-block" publicationscontainer>
            <label class="gray-text">Теги</label>

            <div class="publicationsbox">
                @if (Model.Tags.Count != 0)
                {
                    @foreach (var tag in @Model.Tags)
                    {
                        <div class="mrgn" style="display:inline-block">
                            <input type="checkbox"><label>@tag.TagName</label><br>
                        </div>
                    }
                }
                else
                {
                    <div>
                        <label> Не добавлено ни одного тега.</label>
                    </div>
                }
            </div>
        </div>
        <div>
            <div class="mrgn">
                <input asp-for="Id" class="form-control" readonly="readonly"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class="mrgn">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class="mrgn">
                <textarea asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
        </div>
        <div class="center">
            <form asp-controller="Publication" asp-action="UpdatePublication" method="post">
                <button type="submit" class="btn btn-sm btn-primary min-width-but">
                    Сохранить
                </button>
            </form>
        </div>
    </form>
</div>

FinalProjectMyBlog/FinalProjectMyBlog/Views/Publication/GetAllPublications.cshtml
@model FinalProjectMyBlog.ViewModels.Publications.PublicationViewModel;

<div class="block-reg background-white">

            <div class="lined-block" publicationscontainer>
                <label class="gray-text">Все публикации пользователей</label>

                <div class="publicationsbox">
                    @if (Model.Publications.Count != 0)
                    {
                        @foreach (var publication in @Model.Publications)
                        {
                    <div class="datadiv">
                        <div>
                            <label class="gray-text">Название:</label>
                            <label> @publication.Title</label>
                        </div>

                        <div>
                            <label class="gray-text">Текст публикации:</label>
                            <label> @publication.Text</label>
                        </div>

                        <div>
                            <label class="gray-text">Дата публикации:</label>
                            <label> @publication.Date</label>
                        </div>
                        <div>
                            <label class="gray-text">Пользователь:</label>
                            <label> @publication.UserName</label>
                        </div>
                    </div>
                        }
                    }
                    else
                    {
                        <div>
                            <label> В блогах пока нет публикаций.</label>
                        </div>
                    }
                </div>
            </div>
</div>